[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting_program = "FYtczwQhSXgwhbfQkhfx2dyhaG8ZXsqqN87zNji7SunD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
