[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_core_program = "DzskNoDDBxdS1y3mAxnZMwJQAAYg7CVMfqF6rXxaj2w6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
